# Generated by Django 4.1 on 2022-08-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
