# Generated by Django 4.1 on 2022-08-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0003_pokemon_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='pokemon_slot_1',
            field=models.IntegerField(default=0),
        ),
    ]
