# Generated by Django 4.1 on 2022-08-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0004_alter_trainer_pokemon_slot_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=60)),
                ('base_damage', models.IntegerField(default=3)),
                ('base_accuracy', models.IntegerField(default=3)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='accuracy',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='attack_slot_1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='attack_slot_2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='attack_slot_3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='attack_slot_4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='defence',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='health',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='offence',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokedex_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='reqExp',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='speed',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.trainer'),
        ),
    ]
