# Generated by Django 4.1 on 2022-08-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0005_attacks_pokemon_accuracy_pokemon_attack_slot_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='clicks',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
