# Generated by Django 4.1 on 2022-08-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0009_alter_appuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='name',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
