# Generated by Django 4.1 on 2022-08-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0010_pokemon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='pokemon_slot_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='pokemon_slot_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='pokemon_slot_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='pokemon_slot_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='pokemon_slot_6',
            field=models.IntegerField(default=0),
        ),
    ]
