# Generated by Django 4.1 on 2022-08-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0012_alter_pokemon_attack_slot_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacks',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
