# Generated by Django 4.1 on 2022-08-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0013_alter_attacks_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacks',
            name='color',
            field=models.CharField(default='white', max_length=20),
        ),
    ]
