# Generated by Django 4.1 on 2022-08-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0014_attacks_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacks',
            name='color',
            field=models.CharField(default='default-color', max_length=20),
        ),
    ]
